let actionTypes = {
    GET_ALL_USERS:"GET_ALL_USERS",                 
    GET_SINGLE_USER:"GET_SINGLE_USER",             
    UPDATE_USER:"UPDATE_USER",                                      
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_SEARCH_PRODUCTS:"GET_SEARCH_PRODUCTS",
    GET_PRODUCTS_BY_PAGE:"GET_PRODUCTS_BY_PAGE",         
    GET_SINGLE_PRODUCT:"GET_SINGLE_PRODUCT",
    ADD_REVIEW:"ADD_REVIEW",                      
    GET_ALL_REVIEWS:"GET_ALL_REVIEWS",
    GET_SINGLE_PRODUCT_REVIEWS:"GET_SINGLE_PRODUCT_REVIEWS",
    UPDATE_REVIEW:"UPDATE_REVIEW",
    ADD_TO_CART:"ADD_TO_CART",                     
    GET_ALL_CART_ITEMS:"GET_ALL_CART_ITEMS",  
    CLEAR_CART:'CLEAR_CART',                 
    GET_ALL_ORDERS:"GET_ALL_ORDERS",
    GET_SINGLE_ORDER:"GET_SINGLE_ORDER",
}


export default actionTypes